### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by ChrisB85**
##### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] New feature
- [ ] Refactoring
- [x] Other, please describe:
New language support
##### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

##### The PR fulfills these requirements:

- [ ] When resolving/implementing a specific issue, it's referenced in the PR's title (e.g. `fix #xxx` or `implement #xxx`, where "xxx" is the issue number)
- [ ] You have tested your changes on the branch you wish to merge
- [ ] The changes are working

If adding a **new feature**, the PR's description includes:

- [ ] The reason for this new feature to be added
- [ ] The use of this new feature
- [ ] If available, a link to an existing feature request ticket

### CODE REVIEW

**Comment by Psychokiller1888** [comment]
Thanks! You need two things, one functional, the other for your own pride:

- Adding PL as supported in the install file
- Adding yourself in the maintainers in the install file ;)

**Comment by ChrisB85** [comment]
> Thanks! You need two things, one functional, the other for your own pride:
> 
> * Adding PL as supported in the install file
> * Adding yourself in the maintainers in the install file ;)

Done, but now skill validation is failing:
```skill_DateDayTimeYear invalid
 Installer:
  schema errors in DateDayTimeYear.install:
    - 'pl' does not match '^(en)|(de)|(fr)|(it)$'```

**Comment by Psychokiller1888** [comment]
Yep, it fails because it is not yet officially supported. I just updated the validator to allow pl

**Comment by Psychokiller1888** [comment]
Update your SK to 1.9.2 and it will validate with PL

**Comment by Psychokiller1888** [comment]
Confirmed as valid, Sonarcloud is a Sonarcloud plugin bug, but validation is now ok

**Pull request merged**
